import os
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer


def _parse_numeric(series: pd.Series) -> pd.Series:
    """
    Cleans non-numeric characters from a string series and converts it to floats.
    """
    cleaned = series.astype(str).str.replace(r"[^\d\.]", "", regex=True)
    return pd.to_numeric(cleaned, errors="coerce")


def _minmax(series: pd.Series) -> pd.Series:
    """
    Performs Min-Max normalization on a series (0 to 1 range).
    Handles edge cases where max equals min.
    """
    min_val = series.min()
    max_val = series.max()
    if pd.isna(min_val) or pd.isna(max_val) or max_val == min_val:
        return pd.Series([0.5] * len(series), index=series.index)
    return (series - min_val) / (max_val - min_val)


def get_data():
    """
    Main data retrieval function.
    1. Loads the pre-processed Humanitarian Risk data.
    2. Merges and calculates the 'Transport Constraint' index.
    3. Re-calculates PCA including the new Transport Constraint dimension.
    """
    # Path to the file generated by the preprocessing notebook
    path = os.path.join('data', 'processed_risk_data.csv')

    try:
        df = pd.read_csv(path)
    except FileNotFoundError:
        print(f"Error: Could not find {path}. Ensure the preprocessing notebook has been run!")
        return pd.DataFrame()

    # --- Transport Constraint Index Calculation & PCA Update ---
    try:
        # Load raw infrastructure and demographic data
        transport_df = pd.read_csv(os.path.join('data', 'transportation_data.csv'))
        demo_df = pd.read_csv(os.path.join('data', 'demographics_data.csv'))
        geo_df = pd.read_csv(os.path.join('data', 'geography_data.csv'))

        # Clean numeric columns (remove commas, text, etc.)
        demo_df["Total_Population"] = _parse_numeric(demo_df["Total_Population"])
        geo_df["Land_Area"] = _parse_numeric(geo_df["Land_Area"])

        transport_cols = [
            "airports_paved_runways_count",
            "airports_unpaved_runways_count",
            "roadways_km",
            "railways_km",
            "waterways_km",
        ]
        for col in transport_cols:
            transport_df[col] = pd.to_numeric(transport_df[col], errors="coerce")

        # Merge datasets onto the main dataframe
        df = df.merge(transport_df, on="Country", how="left")
        df = df.merge(demo_df[["Country", "Total_Population"]], on="Country", how="left")
        df = df.merge(geo_df[["Country", "Land_Area"]], on="Country", how="left")

        pop = df["Total_Population"]
        area = df["Land_Area"]

        # Helper to calculate density per population or land area
        def _per_unit(values: pd.Series) -> pd.Series:
            # Prefer per-capita (per 1M people), fallback to per-area (per 1000 sq km) if pop is missing
            per_pop = values / pop * 1_000_000
            per_area = values / area * 1_000
            return per_pop.where(pop.notna() & (pop > 0), per_area)

        # Aggregate runways (paved + unpaved)
        runways_total = df["airports_paved_runways_count"].fillna(0) + df["airports_unpaved_runways_count"].fillna(0)

        metrics = pd.DataFrame(
            {
                "runways_density": _per_unit(runways_total),
                "roadways_density": _per_unit(df["roadways_km"]),
                "railways_density": _per_unit(df["railways_km"]),
                "waterways_density": _per_unit(df["waterways_km"]),
            }
        )

        # 1. Fill NaNs with median (neutral imputation)
        # 2. Log scale to reduce skewness of infrastructure distribution
        # 3. Min-Max normalize to 0-1 range
        metrics = metrics.apply(lambda s: s.fillna(s.median()), axis=0)
        metrics = metrics.clip(lower=0)
        metrics_log = metrics.apply(np.log1p)
        metrics_norm = metrics_log.apply(_minmax, axis=0)

        # 'Transport Supply' is the average of the normalized infrastructure metrics
        transport_supply = metrics_norm.mean(axis=1)

        # 'Transport Constraint' is the inverse of supply (High Constraint = Low Supply)
        df["Transport Constraint"] = 1 - transport_supply
        df["Transport Supply"] = transport_supply

        # --- RE-CALCULATE PCA (Including 5th Dimension) ---
        # We need to update PC1 and PC2 because they were originally calculated
        # on only 4 risks in the notebook.

        risk_features = [
            'Economic Risk',
            'Social Risk',
            'Infrastructure Risk',
            'Demographic Risk',
            'Transport Constraint'
        ]

        # Prepare feature matrix
        X = df[risk_features].copy()

        # Handle missing values (Impute with Mean to avoid PCA crash)
        imputer = SimpleImputer(strategy='mean')
        X_imputed = imputer.fit_transform(X)

        # Apply PCA to reduce to 2 dimensions
        pca = PCA(n_components=2)
        components = pca.fit_transform(X_imputed)

        # Update DataFrame with new PCA coordinates
        df['PC1'] = components[:, 0]
        df['PC2'] = components[:, 1]

        # print("PCA updated successfully with 5 dimensions.")

    except Exception as exc:
        print(f"Warning: Transport/PCA data pipeline failed: {exc}")
        # Return base dataframe if transport pipeline fails, to prevent app crash
        return df

    return df