import pandas as pd
import os


def get_data():
    """
    Loads the pre-processed Humanitarian Risk data.
    The data (including Transport Constraint and PCA) is now fully computed
    in the preprocessing notebook.
    """
    # Path to the file generated by the preprocessing notebook
    path = os.path.join('data', 'processed_risk_data.csv')

    try:
        df = pd.read_csv(path)
        # Ensure numeric columns are strictly numeric in case of loading issues
        cols_to_numeric = ['Economic Risk', 'Social Risk', 'Infrastructure Risk',
                           'Demographic Risk', 'Transport Constraint', 'PC1', 'PC2']

        for col in cols_to_numeric:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        return df

    except FileNotFoundError:
        print(f"Error: Could not find {path}. Ensure the preprocessing notebook has been run!")
        return pd.DataFrame()
    except Exception as e:
        print(f"An unexpected error occurred while loading data: {e}")
        return pd.DataFrame()